"""
Thinklet API — Pydantic models
"""

from __future__ import annotations
from datetime import datetime
from typing import List, Optional
from enum import Enum
from pydantic import BaseModel, Field


class Visibility(str, Enum):
    public   = "public"
    unlisted = "unlisted"
    private  = "private"


# ── Request models ─────────────────────────────────────────────────────────

class ThinkletCreate(BaseModel):
    code:        str              = Field(..., description="Complete Thinklet React component code")
    title:       str              = Field(..., max_length=60, description="Short descriptive title")
    description: str              = Field(..., max_length=200, description="One-sentence description")
    tags:        List[str]        = Field(default_factory=list)
    visibility:  Visibility       = Field(default=Visibility.public)


class ThinkletRemixCreate(BaseModel):
    """Payload for remixing an existing Thinklet. The adapted code is generated by Claude."""
    code:        str              = Field(..., description="Adapted Thinklet React component code")
    title:       str              = Field(..., max_length=60)
    description: str              = Field(..., max_length=200)
    tags:        List[str]        = Field(default_factory=list)
    visibility:  Visibility       = Field(default=Visibility.public)


# ── Response models ────────────────────────────────────────────────────────

class ThinkletResponse(BaseModel):
    id:           str
    title:        str
    description:  str
    tags:         List[str]
    url:          str             = Field(..., description="Shareable Thinklet URL")
    embed_url:    str             = Field(..., description="Iframe embed URL (for MCP Apps rendering)")
    visibility:   Visibility
    created_at:   datetime
    author:       Optional[str]   = None
    remix_count:  int             = 0
    original_url: Optional[str]   = Field(None, description="Source Thinklet URL if this is a remix")

    class Config:
        use_enum_values = True


class ThinkletSearchResponse(BaseModel):
    results: List[ThinkletResponse]
    total:   int
    query:   str
